namespace DinkCompiler;

using System.Text;

public class PoEntry
{
    public List<string> TranslatorComments { get; set; } = new();
    public List<string> ExtractedComments { get; set; } = new();
    public List<string> Flags { get; set; } = new();
    public string Context { get; set; } = "";
    public string MsgId { get; set; } = "";
    public string MsgStr { get; set; } = "";
    public bool Obsolete { get; set; } = false;
}

public static class PoUtils
{
    public static string EscapePo(string s)
    {
        return s
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\t", "\\t")
            .Replace("\r", "")
            .Replace("\n", "\\n");
    }

    public static string UnescapePo(string s)
    {
        var sb = new StringBuilder(s.Length);
        for (int i = 0; i < s.Length; i++)
        {
            if (s[i] == '\\' && i + 1 < s.Length)
            {
                switch (s[i + 1])
                {
                    case '\\': sb.Append('\\'); i++; break;
                    case '"': sb.Append('"'); i++; break;
                    case 'n': sb.Append('\n'); i++; break;
                    case 't': sb.Append('\t'); i++; break;
                    default: sb.Append(s[i]); break;
                }
            }
            else
            {
                sb.Append(s[i]);
            }
        }
        return sb.ToString();
    }

    private static void WritePoString(StringBuilder sb, string keyword, string value, string linePrefix = "")
    {
        sb.AppendLine($"{linePrefix}{keyword} \"{EscapePo(value)}\"");
    }

    public static void WriteEntry(StringBuilder sb, PoEntry entry)
    {
        string prefix = entry.Obsolete ? "#~ " : "";

        if (!entry.Obsolete)
        {
            foreach (var comment in entry.TranslatorComments)
                sb.AppendLine("# " + comment);
            foreach (var comment in entry.ExtractedComments)
                sb.AppendLine("#. " + comment);
            if (entry.Flags.Count > 0)
                sb.AppendLine("#, " + string.Join(", ", entry.Flags));
        }

        if (!string.IsNullOrEmpty(entry.Context))
            WritePoString(sb, "msgctxt", entry.Context, prefix);
        WritePoString(sb, "msgid", entry.MsgId, prefix);
        WritePoString(sb, "msgstr", entry.MsgStr, prefix);
    }

    private static string WritePotHeader(string rootName)
    {
        var sb = new StringBuilder();
        string date = DateTime.UtcNow.ToString("yyyy-MM-dd HH:mm") + "+0000";
        sb.AppendLine("# Translation template generated by DinkCompiler");
        sb.AppendLine("#");
        sb.AppendLine("msgid \"\"");
        sb.AppendLine("msgstr \"\"");
        sb.AppendLine($"\"Project-Id-Version: {EscapePo(rootName)}\\n\"");
        sb.AppendLine($"\"POT-Creation-Date: {date}\\n\"");
        sb.AppendLine("\"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\\n\"");
        sb.AppendLine("\"Last-Translator: \\n\"");
        sb.AppendLine("\"Language-Team: \\n\"");
        sb.AppendLine("\"Language: \\n\"");
        sb.AppendLine("\"MIME-Version: 1.0\\n\"");
        sb.AppendLine("\"Content-Type: text/plain; charset=UTF-8\\n\"");
        sb.AppendLine("\"Content-Transfer-Encoding: 8bit\\n\"");
        return sb.ToString();
    }

    private static string WritePoHeader(string rootName, string lang)
    {
        var sb = new StringBuilder();
        string date = DateTime.UtcNow.ToString("yyyy-MM-dd HH:mm") + "+0000";
        sb.AppendLine("# Translation file generated by DinkCompiler");
        sb.AppendLine("#");
        sb.AppendLine("msgid \"\"");
        sb.AppendLine("msgstr \"\"");
        sb.AppendLine($"\"Project-Id-Version: {EscapePo(rootName)}\\n\"");
        sb.AppendLine($"\"POT-Creation-Date: {date}\\n\"");
        sb.AppendLine($"\"PO-Revision-Date: {date}\\n\"");
        sb.AppendLine("\"Last-Translator: \\n\"");
        sb.AppendLine("\"Language-Team: \\n\"");
        sb.AppendLine($"\"Language: {EscapePo(lang)}\\n\"");
        sb.AppendLine("\"MIME-Version: 1.0\\n\"");
        sb.AppendLine("\"Content-Type: text/plain; charset=UTF-8\\n\"");
        sb.AppendLine("\"Content-Transfer-Encoding: 8bit\\n\"");
        return sb.ToString();
    }

    public static bool WritePotFile(string rootName, List<PoEntry> entries, string destFile)
    {
        try
        {
            var sb = new StringBuilder();
            sb.Append(WritePotHeader(rootName));
            foreach (var entry in entries)
            {
                sb.AppendLine();
                WriteEntry(sb, entry);
            }
            File.WriteAllText(destFile, sb.ToString(), Encoding.UTF8);
            return true;
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error writing POT file {destFile}: " + ex.Message);
            return false;
        }
    }

    public static bool WritePoFile(string rootName, string lang, List<PoEntry> entries, string destFile)
    {
        try
        {
            var sb = new StringBuilder();
            sb.Append(WritePoHeader(rootName, lang));
            foreach (var entry in entries)
            {
                sb.AppendLine();
                WriteEntry(sb, entry);
            }
            File.WriteAllText(destFile, sb.ToString(), Encoding.UTF8);
            return true;
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error writing PO file {destFile}: " + ex.Message);
            return false;
        }
    }

    private static string ExtractQuotedString(string s)
    {
        s = s.Trim();
        if (s.Length >= 2 && s[0] == '"' && s[s.Length - 1] == '"')
            return UnescapePo(s.Substring(1, s.Length - 2));
        return "";
    }

    private enum ParseState { None, MsgCtxt, MsgId, MsgStr }

    public static (string header, List<PoEntry> entries) ParsePoFile(string content)
    {
        var entries = new List<PoEntry>();
        string header = "";
        var lines = content.Split('\n');
        PoEntry? current = null;
        ParseState state = ParseState.None;
        bool headerParsed = false;

        var translatorComments = new List<string>();
        var extractedComments = new List<string>();
        var flags = new List<string>();

        void FinishEntry()
        {
            if (current == null) return;

            if (!headerParsed && string.IsNullOrEmpty(current.Context) && string.IsNullOrEmpty(current.MsgId))
            {
                header = current.MsgStr;
                headerParsed = true;
            }
            else
            {
                entries.Add(current);
            }
            current = null;
            state = ParseState.None;
        }

        for (int i = 0; i < lines.Length; i++)
        {
            string line = lines[i].TrimEnd('\r');

            bool obsolete = false;
            string processLine = line;
            if (line.StartsWith("#~ "))
            {
                obsolete = true;
                processLine = line.Substring(3);
            }

            if (string.IsNullOrEmpty(line))
            {
                FinishEntry();
                translatorComments.Clear();
                extractedComments.Clear();
                flags.Clear();
                continue;
            }

            if (!obsolete)
            {
                if (line.StartsWith("#. "))
                {
                    extractedComments.Add(line.Substring(3));
                    continue;
                }
                if (line.StartsWith("#: "))
                    continue;
                if (line.StartsWith("#, "))
                {
                    flags.AddRange(line.Substring(3).Split(',').Select(f => f.Trim()));
                    continue;
                }
                if (line.StartsWith("#| "))
                    continue;
                if (line.StartsWith("# ") || line == "#")
                {
                    translatorComments.Add(line.Length > 2 ? line.Substring(2) : "");
                    continue;
                }
            }

            if (processLine.StartsWith("msgctxt "))
            {
                current ??= new PoEntry
                {
                    TranslatorComments = new List<string>(translatorComments),
                    ExtractedComments = new List<string>(extractedComments),
                    Flags = new List<string>(flags),
                    Obsolete = obsolete
                };
                state = ParseState.MsgCtxt;
                current.Context = ExtractQuotedString(processLine.Substring(8));
                continue;
            }
            if (processLine.StartsWith("msgid "))
            {
                current ??= new PoEntry
                {
                    TranslatorComments = new List<string>(translatorComments),
                    ExtractedComments = new List<string>(extractedComments),
                    Flags = new List<string>(flags),
                    Obsolete = obsolete
                };
                state = ParseState.MsgId;
                current.MsgId = ExtractQuotedString(processLine.Substring(6));
                continue;
            }
            if (processLine.StartsWith("msgstr "))
            {
                state = ParseState.MsgStr;
                if (current != null)
                    current.MsgStr = ExtractQuotedString(processLine.Substring(7));
                continue;
            }

            if (processLine.StartsWith("\"") && current != null)
            {
                string value = ExtractQuotedString(processLine);
                switch (state)
                {
                    case ParseState.MsgCtxt: current.Context += value; break;
                    case ParseState.MsgId: current.MsgId += value; break;
                    case ParseState.MsgStr: current.MsgStr += value; break;
                }
            }
        }

        FinishEntry();
        return (header, entries);
    }

    public static List<PoEntry> MergeEntries(List<PoEntry> newEntries, List<PoEntry> existingEntries)
    {
        var existingByCtx = new Dictionary<string, PoEntry>();
        foreach (var entry in existingEntries)
        {
            if (!string.IsNullOrEmpty(entry.Context))
                existingByCtx[entry.Context] = entry;
        }

        var newCtxSet = new HashSet<string>();
        var result = new List<PoEntry>();

        foreach (var newEntry in newEntries)
        {
            newCtxSet.Add(newEntry.Context);

            if (existingByCtx.TryGetValue(newEntry.Context, out var existing))
            {
                var merged = new PoEntry
                {
                    TranslatorComments = existing.TranslatorComments,
                    ExtractedComments = newEntry.ExtractedComments,
                    Context = newEntry.Context,
                    MsgId = newEntry.MsgId,
                    MsgStr = existing.MsgStr,
                    Flags = new List<string>(existing.Flags),
                    Obsolete = false
                };

                if (existing.MsgId != newEntry.MsgId && !string.IsNullOrEmpty(existing.MsgStr))
                {
                    if (!merged.Flags.Contains("fuzzy"))
                        merged.Flags.Add("fuzzy");
                }

                result.Add(merged);
            }
            else
            {
                result.Add(newEntry);
            }
        }

        foreach (var existing in existingEntries)
        {
            if (!string.IsNullOrEmpty(existing.Context) && !newCtxSet.Contains(existing.Context))
            {
                existing.Obsolete = true;
                result.Add(existing);
            }
        }

        return result;
    }
}
